# Generated by Django 5.2.3 on 2025-06-24 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='review',
            field=models.TextField(blank=True, default=''),
        ),
    ]
